-- https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/overview-and-usage-scenarios
USE master;
GO

IF OBJECT_ID('[TESTDB]', '') IS NOT NULL DROP DATABASE [TESTDB];
GO

CREATE DATABASE [TESTDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TESTDB',  FILENAME = N'd:\MSSQL\MSSQL12.MSSQLSERVER\MSSQL\DATA\TESTDB.mdf', SIZE = 128MB, MAXSIZE = UNLIMITED, FILEGROWTH = 128MB), 
FILEGROUP [TESTDB] CONTAINS MEMORY_OPTIMIZED_DATA DEFAULT
( NAME = N'TESTDB_mod', FILENAME = N'd:\MSSQL\MSSQL12.MSSQLSERVER\MSSQL\DATA\TESTDB_mod', MAXSIZE = UNLIMITED)
 LOG ON 
( NAME = N'TESTDB_log', FILENAME = N'd:\MSSQL\MSSQL12.MSSQLSERVER\MSSQL\DATA\TESTDB_log.ldf', SIZE = 128MB, MAXSIZE = 2048MB, FILEGROWTH = 128MB)
GO

USE TESTDB;
GO
-- configure recommended DB option
 ALTER DATABASE CURRENT SET MEMORY_OPTIMIZED_ELEVATE_TO_SNAPSHOT=ON
 GO
 -- memory-optimized table
 CREATE TABLE dbo.table1
 ( c1 INT IDENTITY PRIMARY KEY NONCLUSTERED,
   c2 NVARCHAR(4000))
 WITH (MEMORY_OPTIMIZED=ON)
 GO
 -- non-durable table
 CREATE TABLE dbo.temp_table1
 ( c1 INT IDENTITY PRIMARY KEY NONCLUSTERED,
   c2 NVARCHAR(4000))
 WITH (MEMORY_OPTIMIZED=ON,
       DURABILITY=SCHEMA_ONLY)
 GO
 -- memory-optimized table type
 CREATE TYPE dbo.tt_table1 AS TABLE
 ( c1 INT IDENTITY,
   c2 NVARCHAR(4000),
   is_transient BIT NOT NULL DEFAULT (0),
   INDEX ix_c1 HASH (c1) WITH (BUCKET_COUNT=1024))
 WITH (MEMORY_OPTIMIZED=ON)
 GO
